### ISSUE TITLE
Cache location is not configurable

### ISSUE THREAD

**Issue by pipedreambomb** [dwaring87/rtm-api#6]
I was getting an error using RTM-API from within AWS Lambda because it was trying to write to a cache in a location which I did not have permission to access. I found [this thread](https://forums.aws.amazon.com/thread.jspa?threadID=174119) explaining that I was supposed to store files in the /tmp directory. As such, changing this line in `src/utils/taskIds.js:9`:

``` const FILE = path.normalize(os.homedir() + '/' + FILENAME); ```

to:

```  const FILE = path.normalize('/tmp/' + FILENAME); ```

fixed the issue for me. It would be good if users could configure this somehow. I think I'm done with this project now, but if it ever breaks and I need to update the RTM-API dependency, obviously I will lose the changes.

**Comment by dwaring87** [comment]
The location of the cache file is now configurable in the `config.js` file or by setting the `RTM_INDEX_CACHE` environment variable.
